language: ruby
bundler_args: --without development
before_install:
  - gem update bundler
rvm:
  - "1.9"
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3.3"
  - "2.4.0"
  - "jruby-19mode"
  - "jruby-18mode"
  - "rbx-2"
script: bundle exec rspec
